### ISSUE TITLE
Compilation is broken

### ISSUE THREAD

**Issue by WebFreak001** [CyberShadow/DFeed#150]
Trying to run `dub` with latest compiler:

```
     Pre-gen Running commands for openssl
    Starting Performing "debug" build using /usr/bin/dmd for x86_64.
    Building dfeed ~twitter-delete: building configuration [application]
src/dfeed/sinks/subscriptions.d(167,1): Deprecation: usage of the `body` keyword is deprecated. Use `do` instead.
src/dfeed/sinks/subscriptions.d(176,1): Deprecation: usage of the `body` keyword is deprecated. Use `do` instead.
src/dfeed/sinks/subscriptions.d(660,1): Deprecation: usage of the `body` keyword is deprecated. Use `do` instead.
src/dfeed/web/user.d(95,2): Deprecation: usage of the `body` keyword is deprecated. Use `do` instead.
src/dfeed/web/user.d(133,2): Deprecation: usage of the `body` keyword is deprecated. Use `do` instead.
../../.dub/packages/ae-0.0.3101/ae/utils/iconv.d(113,29): Error: Bidirectional control characters are disallowed for security reasons.
../../.dub/packages/ae-0.0.3101/ae/utils/iconv.d(113,29): Error: Bidirectional control characters are disallowed for security reasons.
../../.dub/packages/ae-0.0.3101/ae/utils/iconv.d(114,29): Error: Bidirectional control characters are disallowed for security reasons.
../../.dub/packages/ae-0.0.3101/ae/utils/iconv.d(114,29): Error: Bidirectional control characters are disallowed for security reasons.
Error /usr/bin/dmd failed with exit code 1.
```

Trying to run `dub` with dmd 2.099:

```
Running pre-generate commands for openssl...
Performing "debug" build using /home/webfreak/dlang/dmd-2.099.0/linux/bin64/dmd for x86_64.
dfeed ~twitter-delete: building configuration "application"...
src/dfeed/sinks/subscriptions.d(167,1): Deprecation: Usage of the `body` keyword is deprecated. Use `do` instead.
src/dfeed/sinks/subscriptions.d(176,1): Deprecation: Usage of the `body` keyword is deprecated. Use `do` instead.
src/dfeed/sinks/subscriptions.d(660,1): Deprecation: Usage of the `body` keyword is deprecated. Use `do` instead.
src/dfeed/web/user.d(95,2): Deprecation: Usage of the `body` keyword is deprecated. Use `do` instead.
src/dfeed/web/user.d(133,2): Deprecation: Usage of the `body` keyword is deprecated. Use `do` instead.
src/dfeed/web/mailhide.d(41,17): Error: variable `dfeed.web.mailhide.MailHide.e` no definition of struct `EVP_CIPHER_CTX`
/home/webfreak/dlang/dmd-2.099.0/linux/bin64/dmd failed with exit code 1.
```

Trying to run `./rebuild`:

```
ld: error: undefined symbol: SSL_get_peer_certificate
>>> referenced by openssl.d:430 (lib/ae/net/ssl/openssl.d:430)
>>>               /tmp/.rdmd-1000/rdmd-dfeed.d-715056C6891DBC0F661756A642403FCF/objs/dfeed.o:(_D2ae3net3ssl7openssl14OpenSSLAdapter18getPeerCertificateMFZCQChQChQCgQCf18OpenSSLCertificate)
>>> referenced by openssl.d:480 (lib/ae/net/ssl/openssl.d:480)
>>>               /tmp/.rdmd-1000/rdmd-dfeed.d-715056C6891DBC0F661756A642403FCF/objs/dfeed.o:(_D2ae3net3ssl7openssl14OpenSSLAdapter11updateStateMFZv)
>>> did you mean: SSL_get0_peer_certificate
>>> defined in: /usr/lib/gcc/x86_64-pc-linux-gnu/12.2.1/../../../../lib/libssl.so
collect2: error: ld returned 1 exit status
```

(building with DMD 2.078.3)

**Comment by CyberShadow** [comment]
OpenSSL 3 strikes again!

**Comment by WebFreak001** [comment]
```
OpenSSL 3.0.8 7 Feb 2023 (Library: OpenSSL 3.0.8 7 Feb 2023)
```

on archlinux

**Comment by CyberShadow** [comment]
Fixed and added GitHub Actions workflows to make sure master stays green.
